
version: 2

sources:
  - name: erp
    description: This model represents the source of AdventureWorks sales..
    schema: dev_italo
    tables: 

      - name: creditcard
        description: This table represents the name and id of creditcard.
        columns:
          - name: creditcardid
            description: Primary key of creditcard table.
            tests:
              - unique
              - not_null

      - name: salesterritory
        description: This table represents the names of the territories.
        columns:
          - name: territoryid
            description: Primary key of salesterritory table.
            tests:
              - unique
              - not_null

      - name: customer
        description: This table represents customer.
        columns:
          - name: customerid
            description: Primary key of customer table.
            tests:
              - unique
              - not_null

      - name: person
        description: This table represents customer names.
        columns:
          - name: businessentityid
            description: Primary key of person table.
            tests:
              - unique
              - not_null

      - name: product
        description: This table represents product description.
        columns:
          - name: productid
            description: Primary key of product table.
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: This table represents sales reason description.
        columns:
          - name: salesorderid
            description: Primary key of sales order header sales reason table.
            tests:
              - not_null
          - name: salesreasonid
            description: key of sales order header sales reason table.
            tests:
              - not_null

      - name: salesreason
        description: This table represents sales reason description.
        columns:
          - name: salesreasonid
            description: Primary key of salesreason table.
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: This table represents sales header description.
        columns:
          - name: salesorderid
            description: Primary key of salesorderheader table.
            tests:
              - unique
              - not_null

      - name: salesorderdetail
        description: This table represents sales header description.
        columns:
          - name: salesorderdetailid
            description: Primary key of salesorderdetail table.
            tests:
              - unique
              - not_null

      - name: productcategory
        description: This table represents product category description.
        columns:
          - name: productcategoryid
            description: Primary key of productcategoryid table.
            tests:
              - unique
              - not_null

      - name: productsubcategory
        description: This table represents product subcategory description.
        columns:
          - name: productsubcategoryid
            description: Primary key of product subcategory table.
            tests:
              - unique
              - not_null

      - name: address
        description: This table represents address description.
        columns:
          - name: addressid
            description: Primary key of addres table.
            tests:
              - unique
              - not_null

      - name: stateprovince
        description: This table represents state and province description.
        columns:
          - name: stateprovinceid
            description: Primary key of staten and province table.
            tests:
              - unique
              - not_null

      - name: countryregion
        description: This table represents country and region description.
        columns:
          - name: countryregioncode
            description: Key of country and region table.
            tests:
              - unique
              - not_null
      
      - name: businessentityaddress
        description: This table represents business entity address description.
        columns:
          - name: addressid
            description: Primary key of business entity  addres table.
            tests:
              - unique
              - not_null
